### PR TITLE
Feature/makefile/for/ubuntu/system

### PR DESCRIPTION
**Pull request by balajipachai**
# Description

To run baseline locally, the command in place is `make && make start && make test`, this, in turn, invoked bash scripts under `radish34/ops/*.sh` via the Makefile.
Right from the Makefile to the bash scripts under `radish34/ops/*.sh`  `pushd & popd` are being used however on Ubuntu systems these are not valid commands the bash reports error for **pushd & popd**
Running Baseline locally on Ubuntu should be as easy as it is to execute on the Mac system, therefore made the required changes and created this PR.

## Related Issue

**None**

## Motivation and Context

When it comes to Mac running Baseline locally is as good as executing `make && make start && make test`, why not the same on Ubuntu systems?

## How Has This Been Tested

By executing:

`make -f UbuntuMakefile.mk && make start -f UbuntuMakefile.mk && make test -f UbuntuMakele.mk`

OS: Ubuntu 18.04
Node: 11.15.0 

## Types of changes

- Replaced `-dir` with `-d` in bash scripts, as `-dir` was causing the if statements in bash scripts to stop from executing

    - Since `-dir` was failing the bash scripts thus created `ubuntu` under `ops` directory and moved the required bash scripts inside `ops/ubuntu` from `ops`.

- Replaced `pushd & popd` with `cd & cd..` in Makefile and in bash scripts wherever applicable

- Added a new Makefile for Ubuntu namely `UbuntuMakefile.mk`

- Updated README, added a command for running Baseline locally on Ubuntu system, the command is `make -f UbuntuMakefile.mk && make start -f UbuntuMakefile.mk && make test -f UbuntuMakefile.mk`

 ## Checklist

- Executed the above command on my system, the make command executed successfully.

## Note:

- Instead of having different bash scripts for Ubuntu and Mac, I tried adding If-else in the existing bash scripts, however, that was again resulting into the error generated by `-dir`, thus, created different directory altogether for bash scripts for Ubuntu and replaced `-dir` with `-d`

I hope it helps.

### CODE REVIEW

**Comment by balajipachai** [comment]
> SHELL:=/bin/bash

I tried with that one, yet I was getting errors for pushd and popd used in radish34/package.json's `build:contracts` scripts that uses pushd and popd.

However, `-dir` in the bash files causes the if condition to fail with:

```
./build.sh: line 3: conditional binary operator expected
./build.sh: line 3: syntax error near `./node_modules'
./build.sh: line 3: `git diff --exit-code --quiet HEAD ./package.json && if [ $? -ne 0 ] || [[ ! -dir ./node_modules ]]; then npm ci; fi'
```

**Comment by kthomas** [comment]
> > SHELL:=/bin/bash
> 
> I tried with that one, yet I was getting errors for pushd and popd used in radish34/package.json's `build:contracts` scripts that uses pushd and popd.
> 
> However, `-dir` in the bash files causes the if condition to fail with:
> 
> ```
> ./build.sh: line 3: conditional binary operator expected
> ./build.sh: line 3: syntax error near `./node_modules'
> ./build.sh: line 3: `git diff --exit-code --quiet HEAD ./package.json && if [ $? -ne 0 ] || [[ ! -dir ./node_modules ]]; then npm ci; fi'
> ```
> 
> Thus, went ahead and created a new Makefile and the bash scripts.

We need to address these changes without adding a second branch to maintain. A single `Makefile` and single version of each script under `ops/` will work. Just need to marry up the work you have done on your branch with this strategy. Let me review and see how close the two branches are. I can share my branch with you as well and we can take the best of both worlds.

Thanks for your effort on this 👍

**Comment by balajipachai** [comment]
> > > SHELL:=/bin/bash
> > 
> > 
> > I tried with that one, yet I was getting errors for pushd and popd used in radish34/package.json's `build:contracts` scripts that uses pushd and popd.
> > However, `-dir` in the bash files causes the if condition to fail with:
> > ```
> > ./build.sh: line 3: conditional binary operator expected
> > ./build.sh: line 3: syntax error near `./node_modules'
> > ./build.sh: line 3: `git diff --exit-code --quiet HEAD ./package.json && if [ $? -ne 0 ] || [[ ! -dir ./node_modules ]]; then npm ci; fi'
> > ```
> > 
> > 
> > Thus, went ahead and created a new Makefile and the bash scripts.
> 
> We need to address these changes without adding a second branch to maintain. A single `Makefile` and single version of each script under `ops/` will work. Just need to marry up the work you have done on your branch with this strategy. Let me review and see how close the two branches are. I can share my branch with you as well and we can take the best of both worlds.
> 
> Thanks for your effort on this

Absolutely, let's come up with the best solution.

**Comment by kthomas** [comment]
@balajipachai see #125

**Comment by balajipachai** [comment]
> @balajipachai see #125

Sure, it looks good, then I guess, we should go ahead and close this PR, as it has been addressed in #125

**Comment by balajipachai** [comment]
Since @kthomas has created #125 which addresses this issue and maintains only one Makefile and ensures the make command executes on Ubuntu system thus closing this PR.

**Pull request closed without merging**
