### PR TITLE
Baseline chain dashboard added to examples folder

### PR DESCRIPTION
**Pull request by sekmet**
# Description

There is a folder in the Baseline Protocol Repo that contains the code for a service called "Commitment Manager". It allows you to set the type of ethereum blockchain client and the specific blockchain instance on which you will manage commitments (merkle-trie, proofs) by configuring the service's environment variables.

Use the Commitment Manager to start a baselined workflow on a private Besu blockchain instance, run the workflow several times to successfully deposit commitments into the shield contract on that blockchain. Then, write a switch function and user interface that allows an admin to switch from that private Besu blockchain to the public blockchain via Infura. Minimally, new baseline worksteps/workflows will now go to a public testnet/mainnet.

Hackathon: Baseline Protocol 2020 Hackathon
Baseline Chain Switcher

Bounty: https://gitcoin.co/issue/ethereum-oasis/baseline-roadmap/162/100024422

## Related Issue

Issue: https://github.com/ethereum-oasis/baseline-roadmap/issues/162

## Motivation and Context

Baseline Protocol 2020 Hackathon

## How Has This Been Tested

Tests are located in /examples/baseline-chain-dashboard/tests

## Video Demo

[Baseline Dashboard Demo](https://youtu.be/Nm9v373pL0s)

### Alpha Release [0.1.0] 2021-01-28
- [x] started project Baseline Chain Switcher Demo and Components
- [x] added UI Dashboard

## [0.1.1] 2021-01-29
- [x] added commit-mgr service tests report to dashboard
- [x] commit-mgr should be configurable via env vars such that it can use Infura as its web3 provider
- [ ] a repeatable test suite should be written to ensure baseline transactions can be submitted through Infura
- [x] Shield.sol and Verifier.sol contracts should be deployed on a public testnet/mainnet (verifiable via etherscan or similar)
- [x] root/leaves of on-chain merkle-tree in Shield contract should match root/leaves of off-chain tree stored in mongo
- [ ] commitments made in private Besu network should be replicated on public testnet/mainnet

### Bonus features:
- [x] add Well-Known DID configuration generator
- [x] add simple Baseline Phonebook UI
- [x] use a faucet account or another way to fund public testnet/mainnet transactions so that judges can easily run test suite.
- [x] find a way to securely+efficiently move what has already gone to the private Besu chain instance and move that to the public ethereum mainnet before commencing with new transactions.
- [x] the verification circuit enforces some business logic (instead of using a no-op circuit)
- [x] add a UI that allows the user to configure the commit-mgr service

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bitwiseguy** [comment]
This is really impressive work @sekmet, well done! To get this merged I would love to see this code get moved into `examples/bri-2`. Do you think that is possible instead of creating a new `examples/baseline-chain-dashboard` directory that duplicates much of the `examples/bri-2` code? The `commit-mgr` changes you made could be merged with the existing `examples/bri-2/commit-mgr` code and the ui-dashboard React code could be moved into bri-2 as a `examples/bri-2/dashboard` directory so that it sits beside the `commit-mgr` service and other services of that stack. Let me know what you think!

**Comment by sekmet** [comment]
Hello Mr. Samuel,
Thank you very much! I really loved working with baseline protocol and I
desire to continue to help you guys to improve it.
Thank you for the opportunity, I really appreciated it :)
No problem, I will make updates if needed and re-submit the PR
under examples/bri-2/dashboard.
Please, could you advise me about what features should be implemented into
this dashboard to make it really useful for the project users?
Thank you.

Best regards
Carlos Guimaraes

**Comment by bitwiseguy** [comment]
@sekmet are you on the baseline Slack workspace? If not would you mind joining and messaging me there? Here is the link to join: https://communityinviter.com/apps/ethereum-baseline/join-us

I am happy to work with you to get this merged and we can discuss additional features. I think the conversation will be easier via Slack.

**Review by bitwiseguy — CHANGES_REQUESTED** [review]
@sekmet thanks for these updates. The LICENSE should remain CC0 1.0 Universal as defined at the root of the repo. Do you mind deleting the following files/folders? Many of these files are duplicates from the root level directory of the repo.

* examples/bri-2/did/ (empty directory)
* examples/bri-2/CHANGELOG.md
* examples/bri-2/CODE_OF_CONDUCT.md
* examples/bri-2/CONTRIBUTING.md
* examples/bri-2/LICENSE
* examples/bri-2/LICENSE.md
* examples/bri-2/MAINTAINERS.md
* examples/bri-2/dashboard/
    * CODE_OF_CONDUCT.md
    * CONTRIBUTING.md
    * LICENSE
    * LICENSE.md
    * MAINTAINERS.md

**Comment by sekmet** [comment]
Sure, no problem

**Comment by bitwiseguy** [comment]
Closing this PR. Most of the code introduced here has been moved to PR https://github.com/ethereum-oasis/baseline/pull/313

**Pull request closed without merging**
