### PR TITLE
Adding folder for specifications

### PR DESCRIPTION
**Pull request by danielnorkin**
# Description

Creating a folder for specifications

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by skarred14** [comment]
@danielnorkin thanks for the pr. is it possible to convert the .docx to a .md file using guthub markdown? would be easier to review

**Comment by danielnorkin** [comment]
@skarred14 done

**Comment by skarred14** [comment]
looks like you removed the doc file, and there is no content for either of the 2 file changes. is this intended?

**Comment by danielnorkin** [comment]
I deleted index. The idea was to add this folder as a placeholder so specifications. If there is another location to store specifications documents please let me know.

**Comment by breakpointer** [comment]
Chatted with @danielnorkin about this and we decided to hold off on adding any Specifications document until it's closer to a completed state.

**Pull request closed without merging**
